repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [--maxkb=5000]
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-case-conflict
      - id: detect-private-key
      - id: fix-byte-order-marker
      - id: check-json
      - id: check-yaml
      - id: check-toml

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.8
    hooks:
      - id: clang-format
        files: ^(app|zephyr|src)/.*\.(c|h|cpp|hpp)$
