include:

  - board: eyelash_sofle_left
    shield: nice_view
    cmake-args: -DDTC_OVERLAY_FILE="../../config/eyelash_sofle.keymap"
    artifact-name: eyelash_sofle_left_qwerty
  - board: eyelash_sofle_right
    shield: nice_view_custom
    cmake-args: -DDTC_OVERLAY_FILE="../../config/eyelash_sofle.keymap"
    artifact-name: eyelash_sofle_right_qwerty

  # --- Canary ---
  - board: eyelash_sofle_left
    shield: nice_view
    cmake-args: -DDTC_OVERLAY_FILE="../../config/sofle-canary-zmk.keymap"
    artifact-name: eyelash_sofle_left_canary
  - board: eyelash_sofle_right
    shield: nice_view_custom
    cmake-args: -DDTC_OVERLAY_FILE="../../config/sofle-canary-zmk.keymap"
    artifact-name: eyelash_sofle_right_canary

  # --- Keymappus ---
  - board: eyelash_sofle_left
    shield: nice_view
    cmake-args: -DDTC_OVERLAY_FILE="../../config/sofle-keymappus.keymap"
    artifact-name: eyelash_sofle_left_keymappus
  - board: eyelash_sofle_right
    shield: nice_view_custom
    cmake-args: -DDTC_OVERLAY_FILE="../../config/sofle-keymappus.keymap"
    artifact-name: eyelash_sofle_right_keymappus

  # Settings reset (no keymap needed)
  - board: eyelash_sofle_left
    shield: settings_reset
